[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]
all-features = true

[advisories]
version = 2
ignore = [
]

[bans]
# We don't want any dependencies unless absolutely essential
allow = [
    "xdp",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
]
exceptions = [
]
