[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0 OR MIT"

[dependencies]
aya = { version = "0.13.0", default-features = false }
env_logger = "0.11"
etherparse.workspace = true
object = "0.36"
xdp.workspace = true
