[package]
name = "integ"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
test-utils.workspace = true
xdp.workspace = true
# Generates test packets
etherparse.workspace = true

[dev-dependencies]
# Benchmarking
criterion = { version = "0.5", features = ["html_reports"] }
